# Generated by Django 5.2.4 on 2025-08-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionhistory',
            name='pdf',
        ),
        migrations.AddField(
            model_name='questionhistory',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdfapp.pdfdocument'),
        ),
    ]
