# Generated by Django 5.2.6 on 2025-09-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0003_chathistory_pdfdocument_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionhistory',
            name='document',
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
        migrations.DeleteModel(
            name='QuestionHistory',
        ),
    ]
